application: robohornet-benchmark
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: PIL
  version: latest

handlers:
- url: /issue.*
  script: voting.app
# TEMPORARILY SHUNT ALL OTHER REQUESTS THROUGH THE ACL HANDLER
# Once this is public, flip back to fully static handlers
- url: .*
  script: simple-acl-server.app
  login: required
#- url: /
#  static_files: static/robohornet.html
#  upload: static/robohornet.html
#- url: /(.*)
#  static_files: static/\1
#  upload: .*