application: robohornet-benchmark
version: 1
runtime: python
api_version: 1

handlers:
# TEMPORARILY SHUNT ALL REQUESTS THROUGH THE ACL HANDLER
# Once this is public, flip back to fully static handlers
- url: .*
  script: simple-acl-server.py
  login: required
#- url: /
#  static_files: static/robohornet.html
#  upload: static/robohornet.html
#- url: /(.*)
#  static_files: static/\1
#  upload: .*